stages:
  - build
  - deploy

variables:
  IMAGE_NAME: makkksimka/myapp
  IMAGE_TAG: latest

build_app:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - master

deploy_app:
  stage: deploy
  tags:
    - docker
  script:
    - docker stop myapp  true
    - docker rm myapp  true
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 9090:80 --name myapp $IMAGE_NAME:$IMAGE_TAG
  only:
    - master
